"""
Gradio GUI for NL2Py NLP Interpreter

Provides a web-based interface for translating natural language commands
into executable Python code using the NL2Py modules.
"""

import gradio as gr
from typing import List, Tuple, Optional
import sys
import os

# Add parent path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from nl2py.nlp_interpreter import NLPInterpreter, FileInterpreter, MatchResult


class NLPInterpreterGUI:
    """Gradio-based GUI for the NLP Interpreter."""

    def __init__(self):
        self.interpreter: Optional[NLPInterpreter] = None
        self.modules_loaded = 0

    def initialize_interpreter(self) -> str:
        """Initialize the NLP interpreter and load modules."""
        if self.interpreter is None:
            self.interpreter = NLPInterpreter()
            self.modules_loaded = self.interpreter.load_modules()
        return f"✓ Loaded {self.modules_loaded} method examples from modules"

    def translate_single_line(self, text: str, threshold: float) -> Tuple[str, str, str]:
        """
        Translate a single line of natural language to Python code.

        Returns:
            Tuple of (generated_code, match_info, debug_info)
        """
        if not text.strip():
            return "", "", "Enter a command to translate"

        if self.interpreter is None:
            self.initialize_interpreter()

        result = self.interpreter.interpret(text.strip())

        if result and result.similarity_score >= threshold:
            code = result.generated_code
            match_info = f"""**Module:** {result.module_name}
**Method:** {result.method_name}
**Score:** {result.similarity_score:.2f}
**Matched Example:** {result.matched_example}
**Parameters:** {result.extracted_params}"""
            debug = "Match found"
        else:
            code = f"# No match found for: {text}"
            match_info = "No suitable method found. Try rephrasing or lowering the threshold."
            debug = f"Best score: {result.similarity_score:.2f}" if result else "No results"

        return code, match_info, debug

    def translate_full_text(self, text: str, threshold: float, include_comments: bool) -> Tuple[str, str]:
        """
        Translate multiple lines of natural language to Python code.

        Returns:
            Tuple of (generated_code, summary)
        """
        if not text.strip():
            return "", "Enter commands to translate (one per line)"

        if self.interpreter is None:
            self.initialize_interpreter()

        lines = text.strip().split('\n')
        generated_lines = []
        imports_needed = set()
        matched_count = 0
        total_count = 0

        # Header
        generated_lines.append('"""')
        generated_lines.append('Generated Python code from natural language commands')
        generated_lines.append('Auto-generated by NL2Py NLP Interpreter')
        generated_lines.append('"""')
        generated_lines.append('')

        for line_num, line in enumerate(lines, 1):
            line = line.strip()

            # Skip empty lines and comments
            if not line:
                generated_lines.append('')
                continue

            if line.startswith('#'):
                generated_lines.append(line)
                continue

            total_count += 1
            result = self.interpreter.interpret(line)

            if result and result.similarity_score >= threshold:
                matched_count += 1
                imports_needed.add(result.module_name)

                if include_comments:
                    generated_lines.append(f'# {line}')
                    generated_lines.append(f'# → {result.method_name} (score: {result.similarity_score:.2f})')

                generated_lines.append(result.generated_code)
                generated_lines.append('')
            else:
                if include_comments:
                    generated_lines.append(f'# {line}')
                generated_lines.append(f'# ⚠ No match found')
                generated_lines.append(f'pass  # TODO: Implement manually')
                generated_lines.append('')

        # Build imports
        import_lines = ['from nl2py import modules']
        for module in sorted(imports_needed):
            import_lines.append(f'# Uses: {module}')
        import_lines.append('')
        import_lines.append('')

        final_code = '\n'.join(import_lines + generated_lines)

        # Summary
        summary = f"""**Translation Summary**
- Total commands: {total_count}
- Matched: {matched_count}
- Unmatched: {total_count - matched_count}
- Modules used: {', '.join(sorted(imports_needed)) or 'None'}"""

        return final_code, summary

    def translate_line_by_line(self, text: str, threshold: float) -> List[List[str]]:
        """
        Translate text line by line and return detailed results for each line.

        Returns:
            List of [line_num, original, status, code, score] for dataframe
        """
        if not text.strip():
            return []

        if self.interpreter is None:
            self.initialize_interpreter()

        lines = text.strip().split('\n')
        results = []

        for line_num, line in enumerate(lines, 1):
            line = line.strip()

            if not line:
                results.append([str(line_num), "", "Empty", "", ""])
                continue

            if line.startswith('#'):
                results.append([str(line_num), line, "Comment", line, ""])
                continue

            result = self.interpreter.interpret(line)

            if result and result.similarity_score >= threshold:
                status = "✓ Matched"
                code = result.generated_code
                score = f"{result.similarity_score:.2f}"
            else:
                status = "✗ No match"
                code = "# TODO"
                score = f"{result.similarity_score:.2f}" if result else "0.00"

            results.append([str(line_num), line, status, code, score])

        return results

    def get_top_matches(self, text: str, threshold: float, top_k: int) -> str:
        """Get top K matches for a single command."""
        if not text.strip():
            return "Enter a command to see matches"

        if self.interpreter is None:
            self.initialize_interpreter()

        results = self.interpreter.match(text.strip(), threshold=threshold, top_k=top_k)

        if not results:
            return "No matches found. Try lowering the threshold."

        output = []
        for i, result in enumerate(results, 1):
            output.append(f"### Match {i}")
            output.append(f"**Module:** `{result.module_name}`")
            output.append(f"**Method:** `{result.method_name}`")
            output.append(f"**Score:** {result.similarity_score:.3f}")
            output.append(f"**Example:** {result.matched_example}")
            output.append(f"**Generated Code:**")
            output.append(f"```python\n{result.generated_code}\n```")
            output.append("")

        return "\n".join(output)

    def list_available_methods(self, filter_text: str) -> str:
        """List all available methods, optionally filtered."""
        if self.interpreter is None:
            self.initialize_interpreter()

        # Get unique methods
        methods = {}
        for entry in self.interpreter.method_entries:
            key = f"{entry.module_name}.{entry.method_name}"
            if key not in methods:
                methods[key] = {
                    'module': entry.module_name,
                    'method': entry.method_name,
                    'description': entry.description,
                    'examples': []
                }
            if entry.example_text and entry.example_text != entry.description:
                methods[key]['examples'].append(entry.example_text)

        # Filter
        filter_lower = filter_text.lower().strip()
        if filter_lower:
            methods = {k: v for k, v in methods.items()
                      if filter_lower in k.lower() or filter_lower in v['description'].lower()}

        # Format output
        output = [f"**Available Methods ({len(methods)} found)**\n"]

        current_module = None
        for key in sorted(methods.keys()):
            m = methods[key]
            if m['module'] != current_module:
                current_module = m['module']
                output.append(f"\n### {current_module}\n")

            output.append(f"- **{m['method']}**: {m['description'][:100]}...")
            if m['examples'][:2]:
                for ex in m['examples'][:2]:
                    output.append(f"  - _{ex}_")

        return "\n".join(output)


def create_gui() -> gr.Blocks:
    """Create and return the Gradio interface."""

    gui = NLPInterpreterGUI()

    with gr.Blocks(title="NL2Py Interpreter") as app:

        # Inject dark theme CSS
        gr.HTML("""
        <style>
            /* Dark theme for Gradio */
            :root {
                --primary-color: #4a9eff;
                --primary-hover: #6bb0ff;
                --secondary-color: #7c3aed;
                --background-dark: #0f0f1a;
                --surface-dark: #1a1a2e;
                --surface-light: #252538;
                --border-dark: #363650;
                --text-light: #e8e8f0;
                --text-muted: #9b9baa;
                --warning-color: #ffb84d;
                --error-color: #ff6b6b;
                --success-color: #51cf66;
                --accent-color: #a78bfa;
            }

            /* Main container */
            .gradio-container {
                font-family: 'Inter', sans-serif !important;
                background: var(--background-dark) !important;
                color: var(--text-light) !important;
            }

            /* Headers */
            h1 {
                color: var(--primary-color) !important;
                font-weight: 800 !important;
                letter-spacing: -0.02em !important;
            }
            h2 {
                color: var(--accent-color) !important;
                font-weight: 700 !important;
            }
            h3, h4, h5, h6 {
                color: var(--text-light) !important;
                font-weight: 600 !important;
            }

            /* Blocks and containers */
            .block, .form, .panel {
                background: var(--surface-dark) !important;
                border: 1px solid var(--border-dark) !important;
                border-radius: 8px !important;
                padding: 1.25rem !important;
            }

            /* Column and Row containers */
            .gr-column, .gr-row {
                gap: 1.5rem !important;
            }

            /* Inputs and textareas */
            input, textarea, select {
                background: var(--surface-light) !important;
                color: var(--text-light) !important;
                border: 1px solid var(--border-dark) !important;
                border-radius: 6px !important;
                padding: 0.6rem !important;
            }

            input::placeholder, textarea::placeholder {
                color: var(--text-muted) !important;
                opacity: 0.7 !important;
            }

            input:focus, textarea:focus, select:focus {
                border-color: var(--primary-color) !important;
                outline: none !important;
                box-shadow: 0 0 0 3px rgba(74, 158, 255, 0.15) !important;
            }

            /* Buttons */
            button {
                border-radius: 6px !important;
                font-weight: 600 !important;
                transition: all 0.2s ease !important;
                font-size: 0.95rem !important;
            }

            /* Fix emoji rendering - remove white background */
            button span, .tab-nav button span {
                background: transparent !important;
                filter: grayscale(0%) !important;
                mix-blend-mode: normal !important;
            }

            /* Icons in buttons - ensure visibility */
            button::before {
                margin-right: 0.5rem;
                opacity: 0.9;
            }

            button.primary, .primary-btn {
                background: var(--primary-color) !important;
                color: #ffffff !important;
                border: none !important;
                box-shadow: 0 2px 8px rgba(74, 158, 255, 0.3) !important;
            }

            button.primary:hover, .primary-btn:hover {
                background: var(--primary-hover) !important;
                box-shadow: 0 4px 12px rgba(74, 158, 255, 0.4) !important;
                transform: translateY(-1px) !important;
            }

            button.secondary {
                background: var(--surface-light) !important;
                color: var(--text-light) !important;
                border: 1px solid var(--border-dark) !important;
            }

            button.secondary:hover {
                border-color: var(--primary-color) !important;
                background: var(--surface-dark) !important;
            }

            /* Tabs */
            .tabs {
                border-bottom: 2px solid var(--border-dark) !important;
            }

            .tab-nav button {
                color: var(--text-muted) !important;
                border-bottom: 3px solid transparent !important;
                background: transparent !important;
                padding: 1rem 1.75rem !important;
                font-weight: 600 !important;
                font-size: 1.05rem !important;
                transition: all 0.2s ease !important;
                text-transform: none !important;
            }

            .tab-nav button.selected {
                color: var(--primary-color) !important;
                border-bottom-color: var(--primary-color) !important;
                background: rgba(74, 158, 255, 0.15) !important;
                font-weight: 700 !important;
            }

            .tab-nav button:hover {
                color: var(--primary-hover) !important;
                background: rgba(74, 158, 255, 0.08) !important;
            }

            /* Code blocks */
            pre, code {
                background: var(--surface-light) !important;
                color: var(--text-light) !important;
                border: 1px solid var(--border-dark) !important;
                border-radius: 6px !important;
                font-family: 'JetBrains Mono', 'Fira Code', 'Consolas', monospace !important;
                font-size: 0.9rem !important;
            }

            pre {
                padding: 1rem !important;
                overflow-x: auto !important;
            }

            code {
                padding: 0.2rem 0.4rem !important;
            }

            .code-editor {
                font-family: 'JetBrains Mono', 'Fira Code', 'Consolas', monospace !important;
            }

            /* Dataframe/Table */
            table {
                background: var(--surface-dark) !important;
                color: var(--text-light) !important;
                border: 1px solid var(--border-dark) !important;
            }

            thead {
                background: var(--surface-light) !important;
            }

            th, td {
                border: 1px solid var(--border-dark) !important;
                color: var(--text-light) !important;
            }

            tr:hover {
                background: rgba(74, 158, 255, 0.08) !important;
            }

            tbody tr:nth-child(even) {
                background: rgba(255, 255, 255, 0.02) !important;
            }

            /* Markdown content */
            .markdown-body {
                color: var(--text-light) !important;
                background: var(--surface-light) !important;
                padding: 1rem !important;
                border-radius: 6px !important;
            }

            .markdown-body p, .markdown-body li {
                color: var(--text-light) !important;
                line-height: 1.6 !important;
            }

            .markdown-body strong {
                color: var(--accent-color) !important;
                font-weight: 700 !important;
            }

            .markdown-body code {
                color: var(--primary-color) !important;
                background: var(--surface-dark) !important;
            }

            /* Labels and text */
            label, span, p, div {
                color: var(--text-light) !important;
            }

            label {
                font-weight: 700 !important;
                font-size: 1rem !important;
                margin-bottom: 0.6rem !important;
                display: inline-block !important;
                letter-spacing: 0.01em !important;
            }

            /* Better label visibility */
            .label-wrap span, .label span {
                color: var(--text-light) !important;
                font-weight: 700 !important;
                font-size: 1rem !important;
            }

            /* Section labels - make them stand out more */
            .gr-box label, .block label {
                color: var(--accent-color) !important;
            }

            /* Ensure all text is visible */
            .gr-text, .gr-markdown, .gr-label {
                color: var(--text-light) !important;
            }

            /* Label containers */
            .label-wrap, .label, .svelte-1b19cri {
                color: var(--text-light) !important;
            }

            /* Info boxes and warnings - use theme colors */
            .warning, .info {
                color: var(--text-light) !important;
                background: rgba(255, 184, 77, 0.1) !important;
                border: 1px solid var(--warning-color) !important;
                border-left: 4px solid var(--warning-color) !important;
                padding: 0.75rem !important;
                border-radius: 6px !important;
            }

            .error {
                color: var(--text-light) !important;
                background: rgba(255, 107, 107, 0.1) !important;
                border: 1px solid var(--error-color) !important;
                border-left: 4px solid var(--error-color) !important;
                padding: 0.75rem !important;
                border-radius: 6px !important;
            }

            .success {
                color: var(--text-light) !important;
                background: rgba(81, 207, 102, 0.1) !important;
                border: 1px solid var(--success-color) !important;
                border-left: 4px solid var(--success-color) !important;
                padding: 0.75rem !important;
                border-radius: 6px !important;
            }

            /* Checkboxes */
            input[type="checkbox"] {
                width: 20px !important;
                height: 20px !important;
                cursor: pointer !important;
                accent-color: var(--primary-color) !important;
            }

            /* Sliders */
            input[type="range"] {
                background: var(--surface-light) !important;
                height: 6px !important;
                border-radius: 3px !important;
            }

            input[type="range"]::-webkit-slider-thumb {
                background: var(--primary-color) !important;
                width: 18px !important;
                height: 18px !important;
                border-radius: 50% !important;
                cursor: pointer !important;
                box-shadow: 0 2px 6px rgba(74, 158, 255, 0.4) !important;
            }

            input[type="range"]::-moz-range-thumb {
                background: var(--primary-color) !important;
                width: 18px !important;
                height: 18px !important;
                border-radius: 50% !important;
                cursor: pointer !important;
                border: none !important;
                box-shadow: 0 2px 6px rgba(74, 158, 255, 0.4) !important;
            }

            input[type="range"]::-webkit-slider-thumb:hover {
                background: var(--primary-hover) !important;
                box-shadow: 0 2px 8px rgba(74, 158, 255, 0.6) !important;
            }

            input[type="range"]::-moz-range-thumb:hover {
                background: var(--primary-hover) !important;
                box-shadow: 0 2px 8px rgba(74, 158, 255, 0.6) !important;
            }

            /* Scrollbars */
            ::-webkit-scrollbar {
                width: 10px;
                height: 10px;
            }

            ::-webkit-scrollbar-track {
                background: var(--surface-light);
            }

            ::-webkit-scrollbar-thumb {
                background: var(--border-dark);
                border-radius: 5px;
            }

            ::-webkit-scrollbar-thumb:hover {
                background: var(--primary-color);
            }

            /* Logo container */
            .logo-container {
                display: flex;
                align-items: center;
                gap: 1rem;
                margin-bottom: 2rem;
            }

            .logo-icon {
                width: 48px;
                height: 48px;
            }

            /* Fix all images/icons - no white backgrounds */
            img, svg, .icon {
                background: transparent !important;
                filter: none !important;
            }

            /* Remove white backgrounds from any container */
            * {
                -webkit-font-smoothing: antialiased;
                -moz-osx-font-smoothing: grayscale;
            }
        </style>
        """)

        # Header
        gr.HTML("""
            <div style="text-align: center; margin-bottom: 2rem; padding: 2rem 1rem; background: linear-gradient(135deg, rgba(74, 158, 255, 0.1) 0%, rgba(167, 139, 250, 0.1) 100%); border-radius: 12px; border: 1px solid rgba(74, 158, 255, 0.2);">
                <h1 style="margin: 0; background: linear-gradient(135deg, #4a9eff 0%, #a78bfa 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent; font-size: 2.5rem; font-weight: 800;">NL2Py NLP Interpreter</h1>
                <p style="color: #9b9baa; margin: 0.75rem 0 0 0; font-size: 1.1rem; font-weight: 400;">Translate natural language commands into executable Python code</p>
            </div>
        """)

        # Initialize on load
        status_text = gr.Markdown(value="Loading modules...")

        with gr.Tabs():
            # Tab 1: Single Line Translation
            with gr.Tab("Single Command"):
                with gr.Row():
                    with gr.Column(scale=1):
                        single_input = gr.Textbox(
                            label="Natural Language Command",
                            placeholder="e.g., create compute instance web-server in zone us-central1-a",
                            lines=2
                        )
                        single_threshold = gr.Slider(
                            minimum=0.0, maximum=1.0, value=0.1, step=0.05,
                            label="Similarity Threshold"
                        )
                        single_btn = gr.Button("⟳ Translate", variant="primary")

                    with gr.Column(scale=1):
                        single_code = gr.Code(
                            label="Generated Python Code",
                            language="python",
                            lines=3
                        )
                        single_info = gr.Markdown(label="Match Info")

            # Tab 2: Full Text Translation
            with gr.Tab("Full Translation"):
                with gr.Row():
                    with gr.Column(scale=1):
                        full_input = gr.Textbox(
                            label="Natural Language Commands (one per line)",
                            placeholder="""# Example commands
create compute instance web-server
list all containers
send message to slack channel general""",
                            lines=15,
                            elem_classes=["code-editor"]
                        )
                        with gr.Row():
                            full_threshold = gr.Slider(
                                minimum=0.0, maximum=1.0, value=0.1, step=0.05,
                                label="Threshold"
                            )
                            full_comments = gr.Checkbox(
                                value=True,
                                label="Include comments"
                            )
                        full_btn = gr.Button("⟳ Translate All", variant="primary")

                    with gr.Column(scale=1):
                        full_code = gr.Code(
                            label="Generated Python Code",
                            language="python",
                            lines=20
                        )
                        full_summary = gr.Markdown(label="Summary")

            # Tab 3: Line by Line Analysis
            with gr.Tab("Line-by-Line Analysis"):
                with gr.Row():
                    with gr.Column(scale=1):
                        lbl_input = gr.Textbox(
                            label="Natural Language Commands",
                            placeholder="Enter commands, one per line",
                            lines=10
                        )
                        lbl_threshold = gr.Slider(
                            minimum=0.0, maximum=1.0, value=0.1, step=0.05,
                            label="Threshold"
                        )
                        lbl_btn = gr.Button("▶ Analyze", variant="primary")

                    with gr.Column(scale=1):
                        lbl_table = gr.Dataframe(
                            headers=["Line", "Original", "Status", "Code", "Score"],
                            label="Line-by-Line Results",
                            wrap=True
                        )

            # Tab 4: Explore Matches
            with gr.Tab("Explore Matches"):
                with gr.Row():
                    with gr.Column(scale=1):
                        explore_input = gr.Textbox(
                            label="Command to Explore",
                            placeholder="e.g., upload file to storage",
                            lines=2
                        )
                        with gr.Row():
                            explore_threshold = gr.Slider(
                                minimum=0.0, maximum=1.0, value=0.05, step=0.01,
                                label="Threshold"
                            )
                            explore_topk = gr.Slider(
                                minimum=1, maximum=10, value=5, step=1,
                                label="Top K Results"
                            )
                        explore_btn = gr.Button("◉ Find Matches", variant="primary")

                    with gr.Column(scale=1):
                        explore_results = gr.Markdown(label="Top Matches")

            # Tab 5: Available Methods
            with gr.Tab("📖 Methods Reference"):
                with gr.Row():
                    methods_filter = gr.Textbox(
                        label="Filter methods",
                        placeholder="e.g., postgres, create, bucket",
                        scale=3
                    )
                    methods_btn = gr.Button("◉ Search", scale=1)

                methods_list = gr.Markdown()

        # Event handlers
        single_btn.click(
            fn=gui.translate_single_line,
            inputs=[single_input, single_threshold],
            outputs=[single_code, single_info, status_text]
        )

        single_input.submit(
            fn=gui.translate_single_line,
            inputs=[single_input, single_threshold],
            outputs=[single_code, single_info, status_text]
        )

        full_btn.click(
            fn=gui.translate_full_text,
            inputs=[full_input, full_threshold, full_comments],
            outputs=[full_code, full_summary]
        )

        lbl_btn.click(
            fn=gui.translate_line_by_line,
            inputs=[lbl_input, lbl_threshold],
            outputs=[lbl_table]
        )

        explore_btn.click(
            fn=gui.get_top_matches,
            inputs=[explore_input, explore_threshold, explore_topk],
            outputs=[explore_results]
        )

        methods_btn.click(
            fn=gui.list_available_methods,
            inputs=[methods_filter],
            outputs=[methods_list]
        )

        methods_filter.submit(
            fn=gui.list_available_methods,
            inputs=[methods_filter],
            outputs=[methods_list]
        )

        # Initialize on load
        app.load(
            fn=gui.initialize_interpreter,
            outputs=[status_text]
        )

    return app


def launch(share: bool = False, server_port: int = 7860, **kwargs):
    """
    Launch the Gradio GUI.

    Args:
        share: Whether to create a public share link.
        server_port: Port to run the server on.
        **kwargs: Additional arguments passed to gr.Blocks.launch()
    """
    app = create_gui()
    app.launch(share=share, server_port=server_port, **kwargs)


if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser(description='NL2Py NLP Interpreter GUI')
    parser.add_argument('--share', action='store_true', help='Create public share link')
    parser.add_argument('--port', type=int, default=7860, help='Server port')
    args = parser.parse_args()

    launch(share=args.share, server_port=args.port)
