import sys
from pathlib import Path
from flask import Flask, request, jsonify, send_from_directory

sys.path.append(str(Path(__file__).parent.parent))

from core.block_parser import parse_blocks
from core.code_generator import generate_code_for_block

app = Flask(__name__, static_folder='../frontend')

# Configuration to serve the frontend
@app.route('/')
def serve_frontend():
    return send_from_directory(app.static_folder, 'index.html')

@app.route('/<path:path>')
def serve_static(path):
    return send_from_directory(app.static_folder, path)

# API endpoint
@app.route('/api/parse-blocks', methods=['POST'])
def parse_blocks_endpoint():
    data = request.get_json()
    nl_text = data.get('text', '')
    
    try:
        parsed_blocks = parse_blocks(nl_text)
        return jsonify({
            'success': True,
            'blocks': parsed_blocks
        })
    except Exception as e:
        return jsonify({
            'success': False,
            'error': str(e)
        }), 400
    
@app.route('/api/generate-code', methods=['POST'])
def generate_code_endpoint():
    data = request.get_json()
    block = data.get('block', {})
    
    try:
        # Generates the code for the block
        file_path = generate_code_for_block(block)
        
        # Reads the code generated by the file
        with open(file_path, 'r') as f:
            generated_code = f.read()
        
        return jsonify({
            'success': True,
            'code': generated_code
        })
    except Exception as e:
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500

if __name__ == '__main__':
    app.run(debug=True, port=5000)